apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikareta-web
  namespace: vikareta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vikareta-web
  template:
    metadata:
      labels:
        app: vikareta-web
    spec:
      containers:
      - name: vikareta-web
        image: ghcr.io/aryannkumar/vikareta-web:main
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
